
    export const initModel = {
        lookingFor: '',
        experience: '',
        education: '',
        skills: '',
        description: '',
        image: '',
        hourlyRate: '',
        expectedStartDate: '',
        careerLevel: '',
        equipmentSpecification: '',
        gender: '',
        sundayStTime: '',
        mondayStTime: '',
        sundayEnTime: '',
        mondayEnTime: '',
        tuesStTime: '',
        tuesEnTime: '',
        wedStTime: '',
        wedEnTime: '',
        thusStTime: '',
        thusEnTime: '',
        friEnTime: '',
        friStTime: '',
        saturStTime: '',
        saturEnTime: '',
      }